 export const items =  [
    {
      id: 1,
      category: 'Medicines',
      title: "Combiflame",
      imgSrc: '/Products/med/Combiflame.png',
      description: 'Combiflam Tablet is used to relieve symptoms of muscle pain, arthritis pain.',
      price: '89999',
    },
    {
      id: 5,
      category: 'Medicines',
      title: "Paracetamol",
      imgSrc: '/Products/med/paracetamol.png',
      description: 'Paracetamol Tablet is used to treat fever.',
      price: '49999',
    },
    {
      id: 7,
      category: 'Baby Products',
      title: "Baby-Lotion",
      imgSrc: '/Products/baby-Prod/baby-lotion.png',
      description: 'This lotion is designed with only baby safe ingredients, to help protect your baby skin from dryness',
      price: '29999',
    },
    {
      id: 2,
      category: 'Baby Products',
      title: "Diaper",
      imgSrc: '/Products/baby-Prod/baby-diaper.png',
      description: 'Diaper is a garment that babies wear to absorb waste products.',
      price: '79999',
    },
    {
      id: 6,
      category: 'Medicines',
      title: "Unidic-MR",
      imgSrc: '/Products/med/unidicMr.png',
      description: 'Unidic-MR Tablet is a combination of a muscle relaxant and two pain relieving medicines',
      price: '19999',
    },
    {
      id: 3,
      category: 'Baby Products',
      title: "Baby Oil",
      imgSrc: '/Products/baby-Prod/baby-oil.png',
      description: 'Baby oil is a moisturizing product that is primarily made of mineral oil and fragrance.',
      price: '69999',
    },
    {
      id: 4,
      category: 'General-Items',
      title: "Nicecool Powder",
      imgSrc: '/Products/gen-items/nice-cool.jpg',
      description: 'Nicecool Powder is long lasting cooling treatment of itching sensation, heat rash and burning sensation of the skin',
      price: '29999',
    },
    {
      id: 9,
      category: 'General-Items',
      title: "Handwash",
      imgSrc: '/Products/gen-items/handwash.jpg',
      description: ' Detol handwas kills 99.9% of germs including E. coli and flu virus giving 10 times better protection against skin infections',
      price: '49999',
    },
    {
      id: 8,
      category: 'Medicines',
      title: "DK-50",
      imgSrc: '/Products/med/dk-50.png',
      description: 'DK-50 is used to treat pain, swelling, stiffness, and joint pain',
      price: '89999',
    },

  ]